# Generated by Django 5.2 on 2025-04-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('SalesStaff', 'SalesStaff'), ('WarehouseStaff', 'WarehouseStaff')], default='Admin', max_length=20),
        ),
    ]
